cos:
  tengxun:
    APPID: 1256569009
    #公钥
    accessKey: AKIDiJgneGs24sQlrg4xKSM1tWt1zjEjR43m
    #密钥
    secretKey: ctvjHgy1pMdfV6S8ankWVGl1C8pzua2G
    #桶区域
    bucket: ap-chengdu
    #桶名称
    bucketName: 47-1256569009
    #访问路径
    path: https://47-1256569009.cos.ap-chengdu.myqcloud.com
    #路径前缀
    prefix: wangyang